### ISSUE TITLE
打扰问下，前端的微信小程序构建方式是原创的吗，还是其他工具生成的呢，用tailwind写起来挺爽的👍

### ISSUE THREAD

**Issue by xinde** [jinganix/guess#565]
# Feature Request

### Description
 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by jinganix** [comment]
没有生成工具。整体是原创的，但是中间解决各种流程问题，多多少少有参考其他项目。
