### ISSUE TITLE
some problems on docker-compose up

### ISSUE THREAD

**Issue by varShears** [jinganix/guess#83]
这边我使用了第一种docker-compose的方式进行项目service的启动，但是遇到了一些问题：

关于docker-image的问题 

docker-compose.yml里面使用了两份dockerfile，一个是mysql的镜像 8.3.0，这个镜像是没有的，我降级到了8.0。
另一个是java的镜像，给的版本是openjdk:21-jdk，这个也没有，我目前进行了降级或者寻找其他镜像替代一直卡在了步骤 
 `./build/libs/guess-service.jar /opt/app/` 
这里并报错 
`failed to solve: failed to compute cache key: failed to calculate checksum of ref 8b6209d6-127d-47e7-91b1-07ea347744e7::dmyuxdc7g0e2mx9me1sc8nj9h: failed to walk /var/lib/docker/tmp/buildkit-mount3397668349/build/libs: lstat /var/lib/docker/tmp/buildkit-mount3397668349/build/libs: no such file or directory`

这边想排查下，麻烦作者或其他的参与者可否提供下服务运行的环境等信息，这边也帮助排查一下

**Comment by jinganix** [comment]
mysql和openjdk镜像是存在的:

mysql:8.3.0: https://hub.docker.com/layers/library/mysql/8.3.0/images/sha256-51966d1fd66b5575103e483c13c0e0d33637c634207375dc77894721f49bfc79?context=explore

openjdk:21-jdk: https://hub.docker.com/layers/library/openjdk/21-jdk/images/sha256-c67f402f77197f2e6ae84ff1fca868699ce3b38bfa78604524051420fa2e4383?context=explore

运行之前是否使用`./gradlew build`构建过？
